### ISSUE TITLE
Exception while running example on macOS

### ISSUE THREAD

**Issue by orklann** [google/dart-glfw#13]
`dart example_es2_window.dart` gave this error:

```
2017-08-27 09:53:59.449 dart[867:11447] WARNING: nextEventMatchingMask should only be called from the Main Thread! This will throw an exception in the future.
2017-08-27 09:53:59.449 dart[867:11447] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1349/Misc.subproj/NSUndoManager.m:363
2017-08-27 09:53:59.538 dart[867:11447] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1349/Misc.subproj/NSUndoManager.m:363
2017-08-27 09:53:59.540 dart[867:11447] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffc498d7bb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffd90f0a2a objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffc4992312 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fffc63e5390 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   Foundation                          0x00007fffc636fa93 +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 170
	5   AppKit                              0x00007fffc25900cf -[NSApplication run] + 1200
	6   libglfw.3.dylib                     0x000000010751af7c initializeAppKit + 1420
	7   libglfw.3.dylib                     0x000libc++abi.dylib: terminating with uncaught exception of type NSException
fish: 'dart example_es2_window.dart' terminated by signal SIGABRT (Abort)
```

**Comment by boustrophedon** [comment]
Oh yeah this was the other reason dart and opengl won't work on macos. You can only run graphics stuff from the main thread on macos, and the dart vm runs programs on a different thread. In fact, that's the first line that I put in the Readme two years ago.

You might want to see what the flutter guys are doing about this on iOS, as I vaguely recall some of the people who are now working on that were thinking of ways to deal with this problem even back then.

**Comment by orklann** [comment]
So even no hacks or workarounds on macOS?

**Comment by boustrophedon** [comment]
I am not aware of one right now but as I said, check out the flutter project and see what they do to get their code to work on iOS. I think they might be transpiling to native code in that case though. I am not sure.

**Comment by jtmcdole** [comment]
So it's iOS that you can create multiple contexts / they require you have a context per thread?

**Comment by boustrophedon** [comment]
No idea. I was just assuming that any solution they have for iOS may be workable on macOS as well, because I thought iOS also had the "events on the main thread only" restriction as well.

**Comment by cbracken** [comment]
In Flutter, we have our own VM embedder that manages its own threads, which allows us to delegate work to the appropriate thread. We expose drawing via the `dart:ui` library, which is linked into our embedder and backed by C++ code (with the drawing done by Skia and backed by OpenGL on iOS devices). That gives us control over which thread the drawing happens on.

**Comment by ice1000** [comment]
How can we fix this?

**Comment by lyceel** [comment]
Given the recent announcement about Apple deprecating OpenGL on iOS and MacOS, this likely will never be fixed:

https://arstechnica.com/gadgets/2018/06/the-end-of-opengl-support-other-updates-apple-didnt-share-at-the-keynote/

**Comment by ice1000** [comment]
Oh no
